version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: zhangpei
      MYSQL_PASSWORD: 123456
  mysql_test:
    image: mysql:5.7.18
    ports:
      - 13307:3306
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: zhangpei
      MYSQL_PASSWORD: 123456
    volumes:
      - ./src/main/resources/db/migration/V1__Init_databases.sql:/docker-entrypoint-initdb.d/V1__Init_databases.sql
      - ./src/main/resources/db/migration/V2__create_init_data.sql:/docker-entrypoint-initdb.d/V2__create_init_data.sql

